### PR TITLE
fix: update copy_util to resolve bug issue 192

### PR DESCRIPTION
**Pull request by my3sons**

### CODE REVIEW

**Comment by kmaphoenix** [comment]
Hi @my3sons !

Can you please complete the following tasks:
* Sign the CLA so that we can accept your contribution to the repo

**Review by kmaphoenix — APPROVED** [review]
@my3sons code LGTM! Thanks for the change.

Only thing we need is for you to sign the CLA so you can get credit for your contribution.

**Comment by my3sons** [comment]
Hello @kmaphoenix, I did submit the CLA a couple days ago so let me follow up on that...

**Comment by kmaphoenix** [comment]
@my3sons following up on this:

It looks like you've signed the CLA from your Github account, but the commits came from a different email address when you sent them in.

Can you please try the [CLA link again](https://cla.developers.google.com/), and make sure that you're logged in with the email that you sent the commits from.

**Comment by my3sons** [comment]
Hello @kmaphoenix, sorry for the delay in getting this done, but I think we are good now! Please let me know if you need anything else.

**Pull request merged**
