### PR TITLE
Advanced mode did not manage properly unannotated training phrases

### PR DESCRIPTION
**Pull request by lambertaurelle**
The bulk_create_intent_from_dataframe and bulk_update_intents_from_dataframe did not manage properly training phrases that had no annotations (parameter_id is NA).
Added a condition that solves the issue in src/dfcx_scrapi/tools/dataframe_functions.py file.

Also added an example: 

- a notebook and .py files to help understand how to work with annotated training phrases
- 2 CSV files for sample intent and params

### CODE REVIEW

**Comment by kmaphoenix** [comment]
Discussed with team today.
While the proposed change does fix the immediate issue, the DataFrame generated by [bulk_intent_to_df](https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/main/src/dfcx_scrapi/core/intents.py#L628) `advanced` mode is likely the more systemic issue that needs to be addressed.

@MRyderOC is going to triage since they are working on some similar methods at the moment and have good context for this fix.

**Review by MRyderOC — CHANGES_REQUESTED** [review]
Please make the changes as requested

**Review by MRyderOC — APPROVED** [review]

**Comment by MRyderOC** [comment]
Ready to Merge!

**Review by MRyderOC — APPROVED** [review]

**Review by kmaphoenix — APPROVED** [review]
LGTM

**Pull request merged**
