### PR TITLE
Add Parameter for detect intent

### PR DESCRIPTION
**Pull request by Naveenkm13**

### CODE REVIEW

**Review by kmaphoenix — APPROVED** [review]
LGTM<

**Comment by kmaphoenix** [comment]
@Naveenkm13 there's a conflict with your changes to this notebook and recent changes that were already merged in #210 

Can you see if the changes in #210 are sufficient? If yes, go ahead and delete this branch / PR.
Otherwise, please rebase your changes and update with the current changes to `main` included with your PR.

**Review by kmaphoenix — CHANGES_REQUESTED** [review]
rebase and update with changes to main

**Comment by Naveenkm13** [comment]
Rebased and updated the required changes

**Comment by Naveenkm13** [comment]
> rebase and update with changes to main

Completed..

**Pull request closed without merging**
