### PR TITLE
gather similar items in .gitignore

### PR DESCRIPTION
**Pull request by dcsan**
check PR flow

### CODE REVIEW

**Comment by dcsan** [comment]
@googlebot I signed it!

**Review by kmaphoenix — COMMENTED** [review]
Drop duplicate `venv` from [Line 1](https://github.com/GoogleCloudPlatform/dfcx-scrapi/pull/2/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R1) and then we're good to go.

**Review by kmaphoenix — CHANGES_REQUESTED** [review]
See comment re: changes to duplicate items.

**Comment by dcsan** [comment]
done!

**Review by kmaphoenix — APPROVED** [review]

**Pull request merged**
